In [1]:
import numpy as np
an_array=np.array([1,22,222])
print(type(an_array))

<class 'numpy.ndarray'>


In [2]:
print(an_array.shape)

(3,)


In [3]:
print(an_array[0],an_array[1])

1 22


In [5]:
an_array[0]=1111
print(an_array)

[1111   22  222]


In [6]:
an_array[0]="aa"
print(an_array)

ValueError: invalid literal for int() with base 10: 'aa'

In [8]:
another=np.array([[11,12,13],[22,2,23]])
print(another)
print(another.shape)
print(another[0,1])

[[11 12 13]
 [22  2 23]]
(2, 3)
12


In [10]:
another_1=np.array([[11,12,13],[2,23]])
print(another_1)

[list([11, 12, 13]) list([2, 23])]


In [13]:
ex0=np.zeros((2,2))
print(ex0)

[[0. 0.]
 [0. 0.]]


In [15]:
ex1=np.full((2,2),9.0)
print(ex1)

[[9. 9.]
 [9. 9.]]


In [17]:
ex2=np.eye(2,2)
print(ex2)

[[1. 0.]
 [0. 1.]]


In [21]:
ex3=np.ones((2,1))
print(ex3)

[[1.]
 [1.]]


In [23]:
print(ex3.shape)
print(ex3[0,0])

(2, 1)
1.0


In [25]:
ex4=np.random.random((2,2))
print(ex4)

[[0.4165459  0.70214154]
 [0.9000727  0.73263882]]
